// Generated by CoffeeScript 1.3.3
(function() {
  var prlx,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  prlx = (function() {

    function prlx(el, options, fn) {
      var $document, $window, prop, val, _ref,
        _this = this;
      this.el = el;
      this.options = options;
      this.findPositionOfPageScrolled = __bind(this.findPositionOfPageScrolled, this);

      this.findPositionOfElement = __bind(this.findPositionOfElement, this);

      this.isElPartiallyVisible = __bind(this.isElPartiallyVisible, this);

      this.isElFullyVisible = __bind(this.isElFullyVisible, this);

      this.requestFrameIfNecessary = __bind(this.requestFrameIfNecessary, this);

      $window = $(window);
      $document = $(document);
      this.vendor_prefixes = ["-webkit-", "-moz-", "-ms-", "-o-"];
      this.prefixed_elements = ["border-radius", "transform", "perspective", "perspective-origin", "box-shadow", "background-size"];
      this.document_height = $document.height();
      this.window_height = $window.height();
      this.scroll_top = $window.scrollTop();
      this.scroll_bottom = this.scroll_top + this.window_height;
      this.el_top = this.el.offset().top;
      this.el_height = this.el.height();
      this.running = false;
      this.movers = [];
      $window.on('resize', function() {
        return _this.window_height = $window.height();
      });
      $window.on('scroll', function() {
        _this.scroll_top = $window.scrollTop();
        _this.scroll_bottom = _this.scroll_top + _this.window_height;
        return _this.requestFrameIfNecessary();
      });
      _ref = this.options;
      for (prop in _ref) {
        val = _ref[prop];
        this.movers.push(new this.Mover(prop, val));
      }
      console.log('movers is', this.movers);
    }

    prlx.prototype.requestFrameIfNecessary = function() {
      if (!this.running) {
        requestAnimationFrame(this.move);
      }
      return this.running = true;
    };

    prlx.prototype.Mover = function(prop, val) {
      var end_at, increment_by, options, start_at, trigger_at;
      options = val.split(" ");
      start_at = options[0];
      end_at = options[1];
      increment_by = options[2];
      return trigger_at = options[3];
    };

    prlx.prototype.isElFullyVisible = function() {
      var _ref;
      this.el.trigger('prlx:fullyVisible');
      if (((this.scroll_bottom - this.el_height) > (_ref = this.el_top) && _ref > this.scroll_top)) {
        return true;
      }
    };

    prlx.prototype.isElPartiallyVisible = function() {
      var _ref;
      this.el.trigger('prlx:partiallyVisible');
      if ((this.scroll_bottom > (_ref = this.el_top) && _ref > this.scroll_top - this.el_height)) {
        return true;
      }
    };

    prlx.prototype.findPositionOfElement = function() {
      return (this.el_top - this.scroll_top + this.el_height) / (this.scroll_bottom - this.scroll_top + this.el_height);
    };

    prlx.prototype.findPositionOfPageScrolled = function() {
      return this.scroll_top / (this.document_height - this.window_height);
    };

    prlx.prototype.isFunction = function(obj) {
      return !!(obj && obj.constructor && obj.call && obj.apply);
    };

    prlx.prototype.isObject = function(obj) {
      return obj === Object(obj);
    };

    return prlx;

  })();

  $.fn.prlx = function(options, fn) {
    return $.each(this, function() {
      return new prlx($(this), options);
    });
  };

}).call(this);
